# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:19
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_auto_20161124_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='url',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
