# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0003_auto_20161218_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
